version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: myteam_rails
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - myteam_rails_data:/var/lib/postgresql/data
volumes:
  myteam_rails_data: